var mongoose = require('mongoose');
const moment = require('moment')
var Schema = mongoose.Schema;

var dataSchema = new Schema({
    updated: String,
    to18Donations: String,
    to18RegFee: String,
    to18Crews: String,
    to18RFI: String,
    to18Riders: String,
    mo18Donations: String,
    mo18RegFee: String,
    mo18Crews: String,
    mo18RFI: String,
    mo18Riders: String,
    ab18Donations: String,
    ab18RegFee: String,
    ab18Crews: String,
    ab18RFI: String,
    ab18Riders: String,
    va18Donations: String,
    va18RegFee: String,
    va18Crews: String,
    va18RFI: String,
    va18Riders: String,
    to17Donations: String,
    to17RegFee: String,
    to17Crews: String,
    to17RFI: String,
    to17Riders: String,
    mo17Donations: String,
    mo17RegFee: String,
    mo17Crews: String,
    mo17RFI: String,
    mo17Riders: String,
    ab17Donations: String,
    ab17RegFee: String,
    ab17Crews: String,
    ab17RFI: String,
    ab17Riders: String,
    va17Donations: String,
    va17RegFee: String,
    va17Crews: String,
    va17RFI: String,
    va17Riders: String,
    owTo18Donations: String,
    owTo18RegFee: String,
    owTo18Crews: String,
    owTo18Walkers: String,
    owTo182day: String,
    owTo1815kmWalkers: String,
    owTo1825kmWalkers: String,
    owTo1840kmWalkers: String,
    owTo18RFI: String,
    owTo17Donations: String,
    owTo17RegFee: String,
    owTo17Crews: String,
    owTo17Walkers: String,
    owTo1715kmWalkers: String,
    owTo1725kmWalkers: String,
    owTo1740kmWalkers: String,
    owTo17RFI: String,
    pr18Donations: String,
    pr18RegFee: String,
    pr18Crews: String,
    pr18RFI: String,
    pr18Riders: String,
    pr17Donations: String,
    pr17RegFee: String,
    pr17Crews: String,
    pr17RFI: String,
    pr17Riders: String,
    ml18Donations: String,
    ml18RegFee: String,
    ml18Walkers: String,
    ml18Riders: String,
    ml17Donations: String,
    ml17RegFee: String,
    ml17Walkers: String,
    ml17Riders: String
}, {versionKey: false});

module.exports = mongoose.model('ApiData', dataSchema);